### ISSUE TITLE
Overmind is not showing colors properly

### ISSUE THREAD

**Issue by AlexVPopov** [DarthSim/overmind#6] opened 2017-09-20 09:32 UTC
Hello,

Thank you for the gem. I have a few issues with colors, however I'm not sure wether these are issues with my color scheme of iTerm2, tmux or overmind. I work on OS X with iTerm2. Here are my issues:

1. When I just start sidekiq, the color of the Karate guy is red:

<img width="959" alt="red-karate-guy" src="https://user-images.githubusercontent.com/3239252/30636765-092bfe3c-9dff-11e7-81af-40fbe580c64e.png">

When I start overmind, the Karate guy is black/gray:

<img width="1036" alt="gray-karate-guy" src="https://user-images.githubusercontent.com/3239252/30636830-3353bcc2-9dff-11e7-8363-26bc4a12e802.png">

2. In foreman, different processes have different colors:

<img width="1109" alt="foreman-colors" src="https://user-images.githubusercontent.com/3239252/30636904-78ef8b3a-9dff-11e7-875d-62df416f915d.png">

In overmind, this is not the case (see second image of item 1).

So far I have only described facts and finally my question - are the two points expected behavior or are they due to some misconfiguration in my environment?

**Comment by DarthSim** [comment] 2017-09-21 07:37
Hello,

1. Sidekiq prints its logo via STDERR, that's how it becomes red in some terminals. Since Overmind reads both stdout and stderr through a single pty, it makes no difference between them. I don't think this is a kind of problem, so I don't want to complicate the code, open the second pty and so on just to make Sidekiq logo red, sorry.
Nevertheless, all other coloring made with escape sequences should work fine.

2. Which version of Overmind do you use? Does the problem appear with 1.0.6?

**Comment by DarthSim** [comment] 2017-09-21 07:50
Oh, I found the cause of the second issue. As far as I see, you're using "Solarized Light" theme. The problem is here:

![](http://img.darthsim.me/o5x1k.png)

Overmind uses green, yellow, blue, magenta and cyan for the first five processes. Unlike Foreman, Overmind prints process names bold and bright, and as you see most of these colors are gray-scaled in "Solarized Light". So it's not quite Overmind's issue. I believe I'll make a feature for colors redefinition sometime, but currently, I'm going to close the issue.

**Closed by DarthSim** 2017-09-21 07:50 UTC

**Comment by AlexVPopov** [comment] 2017-09-21 07:52
Hello and thank you for the response.

1. This makes sense. It's definitely a first-world problem, that Karate guy is black in overmind :D 

2. Wow, thank you. As I suspected, it was a problem in my configuration. O.K. thank you. Nevertheless, I'll keep using overmind, as I'd like to test it.

**Comment by AlexVPopov** [comment] 2017-09-21 07:55
I confirm it works with Dark color scheme:

<img width="1021" alt="overmind-dark" src="https://user-images.githubusercontent.com/3239252/30684807-5622ec98-9ebb-11e7-9cb2-833e76c13ff7.png">
